name: Build

on:
  workflow_dispatch:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install ruff
        run: uv tool install ruff

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Format
        # For example, using `pytest`
        run: uvx ruff format

      - name: Lint
        # For example, using `pytest`
        run: uvx ruff check

      - name: Run tests
        # For example, using `pytest`
        run: uvx pytest tests
